### ISSUE TITLE
Icon not being displayed in release mode

### ISSUE THREAD

**Issue by srikanth7785** [abhidiwakar/quick_actions_demo#1]
I cloned your repo and ran it on my device..and it is working fine and also displaying nice icons(or may be, images)..all of this in debug mode.

However, when I released an APK and installed that released APK on my phone..it is not showing any icon.. instead it shows a blank dark circle(check the image    ###attached)..for all the 4 options.

I also tried doing it on my own...with guidance from the plugin documentation..even then I ended up the same way..

So..may be there is a issue with the plugin or may be both of us are missing something..

So..I kindly request you to please check it..in the release mode..

Pls do let me know if you find a solution..

Will be waiting to hear from you..

Thank You.
![IMG_20200514_212828](https://user-images.githubusercontent.com/46991810/81957223-ebac8900-9629-11ea-8ec7-c5b4025f20f8.jpg)

**Comment by abhidiwakar** [comment]
Hello @srikanth7785 
I'm sorry for not answering! I was really busy with some big projects. I have now fixed the issue. The problem was due to resourceShrinking in Android. By default, unused resources are removed by flutter in release mode to decrease file size.

Here's what you have to do to solve the issue:
**Step 1**: Open your app level build.gradle (_android/app/build.gradle_)
**Step 2**: Make the following changes in build.gradle
```
buildTypes {
        release {
            //Disabling shrinkResources means you're taking responsibility to remove any unwanted or unused assets in your android/app/main/res folder.
            //App size may increase a little bit depending on the size of unused resources so consider removing them.
            shrinkResources false
            signingConfig signingConfigs.release
        }
    }
```

**Note**: Disabling shrinkResources is not recommended if the minimum file size is important for you or you are not comfortable in deleting unused resources. If you disable shrinkResouces, you have to manually delete unused resources.
